import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { and, desc, eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { accounts, contents, ips, metrics, platformConnections } from "@/db/schema";
import { getCurrentUser } from "@/lib/auth";
import SubmitButton from "@/app/components/submit-button";
import { platformLabel } from "@/lib/platforms";
import "../module.css";
import "../sync.css";

export const dynamic = "force-dynamic";

export default async function AccountDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ ok?: string; error?: string; q?: string; sort?: string }> }) {
  const user = await getCurrentUser(); if (!user) redirect("/login");
  const { id } = await params; const query = await searchParams;
  const [account] = await db.select().from(accounts).innerJoin(ips, eq(accounts.ipId, ips.id)).leftJoin(platformConnections, eq(platformConnections.accountId, accounts.id)).where(and(eq(accounts.id, id), eq(ips.ownerId, user.id))).limit(1);
  if (!account) notFound();
  const works = await db.select({ id: contents.id, title: contents.title, format: contents.format, publishedAt: contents.publishedAt, publishedUrl: contents.publishedUrl,
    views: sql<number>`coalesce(sum(${metrics.views}),0)`, likes: sql<number>`coalesce(sum(${metrics.likes}),0)`, saves: sql<number>`coalesce(sum(${metrics.saves}),0)`, shares: sql<number>`coalesce(sum(${metrics.shares}),0)`,
    followerDelta: sql<number>`coalesce(sum(${metrics.followerDelta}),0)`, leads: sql<number>`coalesce(sum(${metrics.leads}),0)`, revenue: sql<number>`coalesce(sum(${metrics.revenue}),0)`,
  }).from(contents).leftJoin(metrics, eq(metrics.contentId, contents.id)).where(eq(contents.accountId, id)).groupBy(contents.id).orderBy(desc(contents.publishedAt));
  const dailyRows = await db.execute(sql`select metric_date as date,coalesce(sum(views),0)::int as views,coalesce(sum(likes+saves+shares),0)::int as interactions,coalesce(sum(follower_delta),0)::int as followers from metrics m join contents c on c.id=m.content_id where c.account_id=${id} and m.metric_date >= current_date - interval '29 days' group by metric_date order by metric_date`);
  const daily = Array.from(dailyRows).map((row) => ({ date: String(row.date), views: Number(row.views), interactions: Number(row.interactions), followers: Number(row.followers) }));
  const keyword = (query.q || "").toLowerCase(); const filtered = works.filter((work) => !keyword || work.title.toLowerCase().includes(keyword)); if (query.sort === "oldest") filtered.reverse();
  return <main className="module-page"><header className="module-header"><div><Link href="/accounts">← 返回账号矩阵</Link><p>{platformLabel(account.accounts.platform)}</p><h1>{account.accounts.displayName || account.accounts.handle}</h1><span>录入这个账号已经发布的作品，并持续更新每条作品的真实表现。</span></div><div className="module-badge">{works.length} 条作品</div></header>
    {query.ok && <div className="notice success">{query.ok === "sync" ? "获取完成，最新作品和互动数据已同步。" : query.ok === "connection" ? "采集账号已安全保存，现在可以获取数据。" : "保存成功，数据看板已同步更新。"}</div>}{query.error && <div className="notice error">{query.error === "connection" ? "请先配置采集账号。" : query.error === "sync" ? `获取失败：${account.platform_connections?.lastError || "请检查采集服务配置"}` : query.error === "credential" ? "账号配置保存失败，请检查输入和加密密钥。" : query.error === "file_type" ? "仅支持 .xlsx 或 UTF-8 .csv 文件。" : query.error === "columns" ? "缺少“作品标题”或“数据日期”列，请使用模板列名。" : query.error === "empty_file" ? "文件中没有可导入的数据行。" : query.error === "csv" ? "所有数据行均导入失败，请检查数据日期。" : "保存失败，请检查日期和必填数据。"}</div>}
    <section className="module-card sync-panel"><div><h2>获取最新平台数据</h2><p>{account.platform_connections ? `连接状态：${account.platform_connections.status === "ready" ? "已就绪" : "异常"}。凭据已加密保存，页面不会回显密码。` : "首次使用请配置平台登录账号。生产环境更推荐使用平台官方授权令牌。"}</p>{account.accounts.lastSyncedAt && <small>上次获取：{account.accounts.lastSyncedAt.toLocaleString("zh-CN")}</small>}</div><div className="sync-actions"><details><summary>{account.platform_connections ? "更新采集账号" : "配置采集账号"}</summary><form className="credential-form" action={`/api/accounts/${id}/connection`} method="post" autoComplete="off"><input name="username" required placeholder="平台登录账号" autoComplete="off"/><input name="password" required type="password" placeholder="平台登录密码" autoComplete="new-password"/><SubmitButton>安全保存</SubmitButton></form></details><form action={`/api/accounts/${id}/sync`} method="post"><SubmitButton>立即获取最新数据</SubmitButton></form></div></section>
    <section className="module-card bulk-import"><div><h2>批量导入作品数据</h2><p>下载统一模板，填写后可直接上传 Excel 或 UTF-8 CSV，一次导入多条作品和每日指标。</p><Link href="/templates/content-metrics-template.csv">下载 CSV 模板</Link></div><form action={`/api/accounts/${id}/contents/import`} method="post" encType="multipart/form-data"><input name="file" type="file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" required/><SubmitButton>一键导入</SubmitButton></form></section>
    <section className="trend-grid"><AccountTrend title="播放趋势" rows={daily} field="views"/><AccountTrend title="点赞·收藏·转发" rows={daily} field="interactions"/><AccountTrend title="粉丝增长" rows={daily} field="followers"/></section>
    <section className="module-workspace"><article className="module-card module-data"><h2>作品数据</h2><form className="filter-form" method="get"><input name="q" defaultValue={query.q || ""} placeholder="搜索作品标题"/><select name="sort" defaultValue={query.sort || "newest"}><option value="newest">最新发布</option><option value="oldest">最早发布</option></select><button>筛选</button></form>
      {!filtered.length ? <div className="empty">还没有作品，请在右侧先添加作品。</div> : <div className="video-list">{filtered.map((work) => <div className="video-card" key={work.id}><div><b>{work.title}</b><small>{work.publishedAt?.toLocaleDateString("zh-CN") || "未填写日期"} · {work.format || "视频"}</small></div><div className="video-metrics"><span>播放<strong>{Number(work.views).toLocaleString()}</strong></span><span>点赞<strong>{Number(work.likes).toLocaleString()}</strong></span><span>收藏<strong>{Number(work.saves).toLocaleString()}</strong></span><span>转发<strong>{Number(work.shares).toLocaleString()}</strong></span><span>增粉<strong>{Number(work.followerDelta).toLocaleString()}</strong></span><span>收入<strong>¥{Number(work.revenue).toLocaleString()}</strong></span></div></div>)}</div>}
    </article><aside className="module-card module-editor"><h2>添加已发布作品</h2><form className="stack-form" action={`/api/accounts/${id}/contents`} method="post"><input type="hidden" name="action" value="content"/><label>作品标题<input name="title" required/></label><label>发布日<input name="publishedDate" type="date" required/></label><label>作品类型<select name="format"><option>短视频</option><option>图文</option><option>直播</option><option>长视频</option></select></label><label>作品链接<input name="publishedUrl" type="url"/></label><SubmitButton>添加作品</SubmitButton></form>
      <hr className="form-divider"/><h2>录入作品每日增量</h2><p>填写该作品当天新增的数据；同一作品同一天再次保存会覆盖修正。</p><form className="stack-form" action={`/api/accounts/${id}/contents`} method="post"><input type="hidden" name="action" value="metric"/><label>选择作品<select name="contentId" required><option value="">请选择</option>{works.map((work) => <option value={work.id} key={work.id}>{work.title}</option>)}</select></label><label>数据日期<input name="metricDate" type="date" required/></label><div className="compact-fields"><label>新增播放<input name="views" type="number" min="0" defaultValue="0"/></label><label>新增点赞<input name="likes" type="number" min="0" defaultValue="0"/></label><label>新增收藏<input name="saves" type="number" min="0" defaultValue="0"/></label><label>新增转发<input name="shares" type="number" min="0" defaultValue="0"/></label><label>粉丝增加<input name="followerDelta" type="number" defaultValue="0"/></label><label>新增线索<input name="leads" type="number" min="0" defaultValue="0"/></label><label>新增收入<input name="revenue" type="number" min="0" step="0.01" defaultValue="0"/></label></div><SubmitButton>保存作品数据</SubmitButton></form></aside></section></main>;
}

function AccountTrend({ title, rows, field }: { title: string; rows: { date: string; views: number; interactions: number; followers: number }[]; field: "views" | "interactions" | "followers" }) {
  const max = Math.max(1, ...rows.map((row) => Math.abs(row[field]))); const tone = field === "interactions" ? "green" : field === "followers" ? "coral" : "";
  return <article className="module-card trend-card"><h2>{title}</h2>{rows.length ? <div className="trend-bars">{rows.map((row) => <i key={row.date} className={`trend-bar ${tone}`} style={{ height: `${Math.max(4, Math.abs(row[field]) / max * 100)}%` }} data-value={`${row.date} ${row[field]}`} title={`${row.date} ${row[field]}`}/>)}</div> : <div className="empty">暂无近30日数据</div>}</article>;
}
