#!/usr/bin/env bash
set -euo pipefail

ROOT="${DEPLOY_ROOT:-/opt/media-platform}"
ACTION="${ACTION:-deploy}"

validate() {
  [[ "$MEDIA_APP_CPU" =~ ^(1\.0|2\.0|4\.0)$ ]]
  [[ "$MEDIA_APP_MEMORY" =~ ^(1g|2g|4g)$ ]]
  [[ "$MEDIA_DATABASE_MEMORY" =~ ^(512m|1g|2g)$ ]]
  [[ "$MEDIA_HOST_PORT" =~ ^[0-9]{4,5}$ ]] && (( MEDIA_HOST_PORT >= 1024 && MEDIA_HOST_PORT <= 65535 ))
  [[ "$MEDIA_BIND_ADDRESS" == "0.0.0.0" || "$MEDIA_BIND_ADDRESS" == "127.0.0.1" ]]
}

compose() {
  docker compose --env-file "$ROOT/shared/.env" --env-file "$1/deploy.resources.env" -f "$1/docker-compose.yml" "${@:2}"
}

mkdir -p "$ROOT/releases" "$ROOT/shared"
if [[ ! -s "$ROOT/shared/.env" ]]; then
  echo "Missing production secrets: $ROOT/shared/.env" >&2
  echo "Create it from .env.example and set POSTGRES_PASSWORD before the first deployment." >&2
  exit 1
fi

if [[ "$ACTION" == "rollback" ]]; then
  CURRENT="$(readlink -f "$ROOT/current" 2>/dev/null || true)"
  TARGET="$(find "$ROOT/releases" -mindepth 1 -maxdepth 1 -type d ! -path "$CURRENT" -printf '%T@ %p\n' | sort -nr | head -n 1 | cut -d' ' -f2-)"
  test -n "$TARGET"
  # Resource files are generated by this script from strict allow-listed values.
  set -a
  source "$TARGET/deploy.resources.env"
  set +a
  compose "$TARGET" up -d --build --remove-orphans
else
  validate
  RELEASE="$ROOT/releases/$RELEASE_SHA"
  mkdir -p "$RELEASE"
  tar -xzf "$ARCHIVE" -C "$RELEASE"
  cat > "$RELEASE/deploy.resources.env" <<EOF
MEDIA_APP_CPU=$MEDIA_APP_CPU
MEDIA_APP_MEMORY=$MEDIA_APP_MEMORY
MEDIA_DATABASE_CPU=1.0
MEDIA_DATABASE_MEMORY=$MEDIA_DATABASE_MEMORY
MEDIA_HOST_PORT=$MEDIA_HOST_PORT
MEDIA_BIND_ADDRESS=$MEDIA_BIND_ADDRESS
EOF
  TARGET="$RELEASE"
  compose "$TARGET" up -d --build --remove-orphans
fi

for _ in $(seq 1 45); do
  if curl -fsS "http://127.0.0.1:${MEDIA_HOST_PORT:-8080}/" >/dev/null; then
    ln -sfn "$TARGET" "$ROOT/current"
    find "$ROOT/releases" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' | sort -nr | tail -n +6 | cut -d' ' -f2- | xargs -r rm -rf
    [[ -n "${ARCHIVE:-}" ]] && rm -f "$ARCHIVE"
    echo "Media active at $MEDIA_BIND_ADDRESS:$MEDIA_HOST_PORT from $TARGET"
    exit 0
  fi
  sleep 2
done

compose "$TARGET" ps
compose "$TARGET" logs --tail=100 nginx app
echo "Media health check failed" >&2
exit 1
